# fly.toml app configuration file generated for dawn-sea-7411 on 2023-05-03T22:03:14+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dawn-sea-7411"
primary_region = "sin"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
